name: Functional Tests And Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: tests-py${{matrix.python-version}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: clone repo
      uses: actions/checkout@v2
    - name: setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: run tests
      run: |
        pip install nox
        nox -e tests
    - name: install coverage prereqs
      run: |
        pip install coverage
    - name: upload coverage
      uses: codecov/codecov-action@v1
